# Generated by Django 3.2.6 on 2022-06-10 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220610_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
