# Generated by Django 3.2.6 on 2022-06-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_vote_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='catalog.book'),
        ),
    ]
