# Generated by Django 3.2.6 on 2022-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220610_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
